//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuRegForm.Models.StuRegFormDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttachments
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public string PhotoAttPath { get; set; }
        public string PhotoAttName { get; set; }
        public string MarksheetAttPath { get; set; }
        public string MarksheetAttName { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
