//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuRegForm.Models.StuRegFormDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StuRegFormEntities : DbContext
    {
        public StuRegFormEntities()
            : base("name=StuRegFormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Board> Board { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<Level> Level { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Zones> Zones { get; set; }
        public virtual DbSet<StudentAddress> StudentAddress { get; set; }
        public virtual DbSet<vwStudentAddress> vwStudentAddress { get; set; }
        public virtual DbSet<StudentSchool> StudentSchool { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<StudentCourse> StudentCourse { get; set; }
        public virtual DbSet<StudentAttachments> StudentAttachments { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<vwStuAllInfo> vwStuAllInfo { get; set; }
    }
}
