//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StuRegForm.Models.StuRegFormDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStudentAddress
    {
        public int StudentId { get; set; }
        public int VoucherNo { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int GenderId { get; set; }
        public long Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ParentName { get; set; }
        public long ParentMobile { get; set; }
        public Nullable<int> PerAddressId { get; set; }
        public Nullable<int> TempAddressId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string PZone { get; set; }
        public string PDistrict { get; set; }
        public int wardNo { get; set; }
        public string StreetName { get; set; }
        public int tWard { get; set; }
        public string tStreet { get; set; }
        public string TZone { get; set; }
        public string TDistrict { get; set; }
    }
}
